# These are supported funding model platforms
#
# ⚠️ This file was inherited from upstream mcMMO and named `nossr50` on four rows
# (github, patreon, custom/paypal.me), which put a Sponsor button on THIS repo that
# collected for a different project. Retargeted 2026-08-18 (owner-supplied handle).
# Credit to upstream lives in README.md and LICENSE, which is where GPL-3.0 wants it.

ko_fi: wulfic
