package com.gmail.nossr50.guards;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;

/**
 * <b>Proves every mixin is actually DECLARED</b> — the inverse of {@link MixinApplicationTest},
 * and the hole §74 found next to it.
 *
 * <p>{@link MixinApplicationTest} proves that <em>if</em> a mixin is declared, its injection still
 * resolves against this Minecraft version. It cannot prove that the mixin is declared at all, and
 * neither could anything else: before this file, {@code grep -rn 'mcmmo.mixins.json' src/test}
 * returned eight files and <b>every single hit was a javadoc mention</b>. Nothing in the suite
 * parsed the {@code mixins} array. The source tree and the manifest agreed by luck.
 *
 * <p><b>Why an undeclared mixin is silent rather than loud, which is the whole reason this exists.</b>
 * {@code injectors.defaultRequire = 1} makes a <em>drifted</em> injection throw at class-load — that
 * is precisely what the {@code assertDoesNotThrow(Class.forName(...))} tests next door rely on for
 * their meaning. An <em>undeclared</em> mixin is the opposite shape. Mixin never attempts to apply
 * it, so the target class loads perfectly cleanly, and the gameplay the mixin implements simply
 * stops happening. No exception, no log line, no red test. Every instrument in this repo watches for
 * transformations that <em>failed</em>; none watched for one that was never <em>attempted</em>.
 *
 * <p><b>Measured, not argued (2026-09-22, §77).</b> Deleting {@code "SnowGolemTrailMixin"} from the
 * manifest and running the whole suite — both tasks, {@code test} and {@code tagBoundTest} — scored
 * <b>174 classes / 1,948 tests / 0 failures / 0 errors</b>, byte-for-byte the recorded green
 * baseline. The mutation reached the runtime (the copy under {@code build/resources/main} contained
 * zero occurrences), so that is a real blind spot and not a stale build. One mixin switched off, and
 * the entire test suite could not tell.
 *
 * <p><b>Why {@code theMixinsWereActuallyApplied} does not cover it either.</b> That guard's floor is
 * {@code >= 20} transformed targets. Deleting one declaration of 41 leaves roughly 35 still carrying
 * their {@code mcmmo$} members, so it passes comfortably — it is built to notice Mixin being absent
 * wholesale, not one entry going missing.
 *
 * <p><b>Anti-vacuity.</b> Two independent parsers have to agree here: a JSON read of the manifest and
 * a filesystem walk of {@code src/main/java}. A one-sided failure — a wrong path, a regex that
 * matches nothing — makes one set empty while the other stays full, so the equality assertions below
 * redden rather than passing on two empty sets. Only a simultaneous double failure could pass
 * quietly, and {@link #theScanFoundARealMixinPopulation()} is the backstop for that: it floors both
 * counts against the {@code MIXINCLASS} record count in {@code scripts/mc-surface.txt}, a manifest
 * generated by an independently-written Python script months earlier.
 *
 * <p><b>Why that floor is DERIVED rather than a literal.</b> The population is a per-band fact, not a
 * constant: {@code master} carries 41 mixins over 36 distinct target classes while all three live
 * bands carry 42 over 37, because 26.3 deleted {@code HoeItem} and with it
 * {@code HoeTillingActionsAccessor}. A hardcoded 41 would be wrong on every band the day it was
 * written. Every mixin file targets at least one class and several files share a target, so
 * {@code files >= distinct targets} holds on every band by construction and moves by itself.
 *
 * <p><b>⚠️ TWO ASSERTIONS WERE WRITTEN HERE, MEASURED UNFALSIFIABLE, AND DELETED. Do not re-add
 * them.</b> The first draft of this file also asserted the opposite direction — that every declared
 * name has a source file — and that {@code "package"} still matched where the sources live. Both
 * looked obviously correct and both <b>can never fail</b>:
 *
 * <ul>
 *   <li>Declaring a name with no class, and drifting the package, were each mutated in. Neither
 *       produced a test failure: Mixin refuses to transform <em>any</em> class under a config it
 *       cannot resolve, so the fork dies with <i>"Mixin transformation of
 *       MixinManifestDeclarationTest failed"</i> before this class loads. <b>Zero JUnit XML, so
 *       there is no result to read</b> — the guard is not merely redundant, it is unreachable.</li>
 *   <li>The package check also carried a "stray {@code @Mixin} file outside the declared package"
 *       assertion. Planting one fired <b>both</b> it and
 *       {@link #everyMixinSourceFileIsDeclaredInTheManifest()} together, so it had no unique domain
 *       either. Its one real contribution — that "add it to the manifest" is the wrong advice for a
 *       file in the wrong package — is folded into that test's failure message instead.</li>
 * </ul>
 *
 * <p>Both conditions <em>are</em> enforced, loudly, by Mixin itself at fork startup, on every test
 * task and every boot. A test in front of that enforcement cannot add to it and can only mislead a
 * reader into thinking this file is what holds the line.
 */
class MixinManifestDeclarationTest {

    private static final Path MANIFEST =
            Path.of("src", "main", "resources", "mcmmo.mixins.json");

    private static final Path MAIN_SOURCES = Path.of("src", "main", "java");

    private static final Path MC_SURFACE = Path.of("scripts", "mc-surface.txt");

    private static final String DECLARED_PACKAGE = "com.gmail.nossr50.fabric.mixin";

    /** {@code @Mixin(...)} on a type, after comments and string literals are blanked. */
    private static final Pattern MIXIN_ANNOTATION = Pattern.compile("@Mixin\\s*\\(");

    // --- The hole §74 named -------------------------------------------------------------------

    @Test
    void everyMixinSourceFileIsDeclaredInTheManifest() {
        final Set<String> undeclared = new TreeSet<>(mixinSourceNames());
        undeclared.removeAll(declaredNames());

        assertTrue(undeclared.isEmpty(), () ->
                "These mixin classes exist in src/main/java but are NOT declared in "
                        + MANIFEST + ", which means Mixin never applies them:\n  "
                        + String.join("\n  ", undeclared)
                        + "\n\nThis does not throw anywhere and does not fail any other test -- the "
                        + "target class loads clean and the gameplay the mixin implements silently "
                        + "stops happening.\n\n"
                        + "FIX: if the class sits under " + DECLARED_PACKAGE + ", add its simple "
                        + "name to the manifest's \"mixins\" array. If it sits ANYWHERE ELSE, adding "
                        + "the name will not help -- every entry resolves relative to that package, "
                        + "so move the file. If the mixin was meant to be retired, delete its source "
                        + "file too.");
    }

    // --- The claim ANOTHER test cites as its own justification ---------------------------------

    @Test
    void theInjectorDefaultRequireIsStillOne() {
        final JsonObject injectors = manifest().getAsJsonObject("injectors");
        assertTrue(injectors != null && injectors.has("defaultRequire"),
                () -> "mcmmo.mixins.json no longer declares injectors.defaultRequire at all.");

        assertEquals(1, injectors.get("defaultRequire").getAsInt(),
                "injectors.defaultRequire is what makes a drifted injection THROW at class-load. "
                        + "MixinApplicationTest's assertDoesNotThrow(Class.forName(...)) tests cite "
                        + "it by name as the reason they are assertions rather than decoration -- "
                        + "lower it and those tests keep passing while proving nothing, with nothing "
                        + "else going red. It is asserted here because it is load-bearing for "
                        + "another file's meaning, not just for this one's.");
    }

    // --- Anti-vacuity: prove both parsers found something ---------------------------------------

    @Test
    void theScanFoundARealMixinPopulation() {
        // Derived, not hardcoded -- see the class javadoc. MIXINCLASS counts DISTINCT target
        // classes; mixin FILES are always at least that many because several files share a target
        // (four LivingEntity*Mixin files alone), and never fewer because every file targets at
        // least one class. Measured: master 41 files / 36 targets, all three live bands 42 / 37.
        final long distinctTargets = mcSurfaceMixinClassCount();

        // The ONE slack literal in this file, and it is deliberately far below the real 36. It is
        // not a claim about the population -- the two equality tests above are. It exists only so a
        // truncated or empty mc-surface.txt cannot quietly turn the derived floor into zero and
        // make everything below it vacuous.
        assertTrue(distinctTargets >= 30,
                () -> "scripts/mc-surface.txt records only " + distinctTargets + " MIXINCLASS "
                        + "entries. That file is the cross-check the floors below are derived from, "
                        + "so a truncated one would make them vacuous. Regenerate it with "
                        + "scripts/extract-mc-surface.py rather than lowering this number.");

        // ⚠️ THE SOURCE SIDE IS FLOORED AND THE MANIFEST SIDE DELIBERATELY IS NOT. A symmetric
        // `declaredNames().size() >= distinctTargets` was written here and then MEASURED REDUNDANT:
        // it can never fire alone. Shrinking the manifest below the floor necessarily leaves source
        // files undeclared, so everyMixinSourceFileIsDeclaredInTheManifest reddens first and louder;
        // and an empty JSON parse makes all 41 look undeclared, which that test also catches. A
        // guard that changes no outcome is decoration -- §74 removed two of those rather than leave
        // them to be tidied away later by someone who could not tell.
        //
        // 🔑 The source side is the OPPOSITE case and is the whole reason this test exists. Measured
        // by mutating the walk's pattern to match nothing: the set difference above becomes
        // {} - declared = {}, so everyMixinSourceFileIsDeclaredInTheManifest PASSES -- vacuously,
        // on an empty derived collection, the §74 shape. Only this assertion noticed. Without it a
        // broken walk reports a clean mixin manifest forever.
        assertTrue(mixinSourceNames().size() >= distinctTargets,
                () -> "the source walk found only " + mixinSourceNames().size() + " @Mixin files "
                        + "against " + distinctTargets + " recorded target classes. A walk that "
                        + "matches nothing makes everyMixinSourceFileIsDeclaredInTheManifest pass on "
                        + "an empty set; this is the assertion that stops it.");
    }

    // --- Plumbing --------------------------------------------------------------------------------

    private static JsonObject manifest() {
        return JsonParser.parseString(read(MANIFEST)).getAsJsonObject();
    }

    /**
     * Every simple class name the manifest declares.
     *
     * <p>Reads {@code client} and {@code server} as well as {@code mixins}. This branch uses only
     * {@code mixins}, but a mixin moved into a side-specific array is still declared, and a scan
     * that ignored those arrays would report it as missing — a false failure that a reader would
     * "fix" by duplicating the entry.
     */
    private static Set<String> declaredNames() {
        final JsonObject root = manifest();
        final Set<String> out = new TreeSet<>();
        for (String key : List.of("mixins", "client", "server")) {
            if (!root.has(key) || !root.get(key).isJsonArray()) {
                continue;
            }
            final JsonArray arr = root.getAsJsonArray(key);
            for (JsonElement el : arr) {
                out.add(el.getAsString());
            }
        }
        return out;
    }

    /** Simple class name of every {@code @Mixin}-annotated file anywhere under src/main/java. */
    private static Set<String> mixinSourceNames() {
        final Set<String> out = new TreeSet<>();
        for (Path p : mixinSourceFiles()) {
            final String file = p.getFileName().toString();
            out.add(file.substring(0, file.length() - ".java".length()));
        }
        return out;
    }

    private static List<Path> mixinSourceFiles() {
        try (Stream<Path> walk = Files.walk(MAIN_SOURCES)) {
            return walk.filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().endsWith(".java"))
                    .filter(p -> MIXIN_ANNOTATION.matcher(strip(read(p))).find())
                    .sorted()
                    .toList();
        } catch (IOException e) {
            throw new UncheckedIOException("could not walk " + MAIN_SOURCES.toAbsolutePath(), e);
        }
    }

    private static long mcSurfaceMixinClassCount() {
        return read(MC_SURFACE).lines().filter(l -> l.startsWith("MIXINCLASS\t")).count();
    }

    private static String read(Path file) {
        try {
            return Files.readString(file, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("could not read " + file.toAbsolutePath(), e);
        }
    }

    /**
     * Blank comments and literals, preserving newlines.
     *
     * <p>⚠️ String literals are handled before char literals on purpose. §74 measured the other
     * order as a genuine false negative: a char literal holding a quote opens a span that swallows
     * the rest of the line. See {@code MixinApplicationTest#strip}, which this mirrors.
     */
    private static String strip(String source) {
        final StringBuilder out = new StringBuilder(source.length());
        final int n = source.length();
        int i = 0;
        while (i < n) {
            final char c = source.charAt(i);
            final char next = i + 1 < n ? source.charAt(i + 1) : '\0';
            if (c == '/' && next == '/') {
                while (i < n && source.charAt(i) != '\n') {
                    i++;
                }
            } else if (c == '/' && next == '*') {
                i += 2;
                while (i < n && !(source.charAt(i) == '*' && i + 1 < n && source.charAt(i + 1) == '/')) {
                    if (source.charAt(i) == '\n') {
                        out.append('\n');
                    }
                    i++;
                }
                i = Math.min(i + 2, n);
            } else if (c == '"' || c == '\'') {
                out.append(c);
                i++;
                while (i < n && source.charAt(i) != c) {
                    i += source.charAt(i) == '\\' ? 2 : 1;
                }
                out.append(c);
                i++;
            } else {
                out.append(c);
                i++;
            }
        }
        return out.toString();
    }
}
